### ISSUE TITLE
Система оценки ситуации для бота

### ISSUE THREAD

**Issue by Kuzgaroth** [Kuzgaroth/ProjectRevival#15]
### Зачем:
Это вторая задача внутри механики отхода бота в укрытие. Теперь необходимо написать логику бота по поиску объекта, анализа его характеристик и внутреннего состояния бота, принятия решения, что дальше делать. 

### Задача:
- [x] Написать _Service_ анализа видимых объектов, реализующий интерфейс, написанный в #7. Ближайший объект заносится в _Blackboard_, при исчезновении объекта или появлении нового ближайшего (отошли от первого ко второму, и теперь он ближайший) так же менять значение
- [x] Написать декоратор, проверяющий условие относительно HP. Активировать ноду со службой при _HP_<75%
- [x] Создать _ENUM_, значения которого обозначают _HP_ меньше 25%, 25-50%, 50-75%, 75-100%. Для декоратора выбрать тип значения(ну и создать новый элемент в _Blackboard_ соответственно) _Enum_ в _Blackboard_ и поставить свой созданный _Enum_
- [x] Создать метод в _PerceptionComponent_ для получения объектов из поля зрения
- [x] При падении _HP_ меньше 50% запускать ноду с пустым _Task_ и выводить сообщение на экран. (Task потом будет использоваться в третьей завершающей задаче)
- [x] Для получения расстояния создать метод в интерфейсе и написать его дефолтную реализацию (смотри https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/GameplayArchitecture/Interfaces/)
- [x] Или реализовать с использованием EQS (В этом случае 1,4,6 пунты считаются выполненными)

### Замечания:
1. Данную задачу можно сделать через _EQS_, если сделаешь, накину бонусы, но тут я ничем не могу помочь по материалам.
2. Пример _UENUM_ есть в _BaseCharacter.h_ или можно нагуглить, в документации есть всё
3. Понять как организовать дерево в _Behavior Tree_ оставляю на тебя
4. Для тренировки можешь создать какстомный _Task_ на _С++_ и там выводить сообщение на экран

**Comment by Kuzgaroth** [comment]
### Дедлайн: 29.11.21 21:00
### Ветка для работы: bot-check-situation

**Comment by fazilhus** [comment]
Поскольку делал через EQS, то первый, четвертый и последний пункты не выполнял
